#:schema node_modules/wrangler/config-schema.json
name = "sublink-worke"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "9159bc16b57e4827a15682b40e995cf1" }
]

[assets]
directory = "./public"
